/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Obrigado2RouteImport } from './routes/obrigado2'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as FinalRouteImport } from './routes/final'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicYuvexpayWebhookRouteImport } from './routes/api/public/yuvexpay-webhook'

const Obrigado2Route = Obrigado2RouteImport.update({
  id: '/obrigado2',
  path: '/obrigado2',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const FinalRoute = FinalRouteImport.update({
  id: '/final',
  path: '/final',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicYuvexpayWebhookRoute =
  ApiPublicYuvexpayWebhookRouteImport.update({
    id: '/api/public/yuvexpay-webhook',
    path: '/api/public/yuvexpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/final': typeof FinalRoute
  '/obrigado': typeof ObrigadoRoute
  '/obrigado2': typeof Obrigado2Route
  '/api/public/yuvexpay-webhook': typeof ApiPublicYuvexpayWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/final': typeof FinalRoute
  '/obrigado': typeof ObrigadoRoute
  '/obrigado2': typeof Obrigado2Route
  '/api/public/yuvexpay-webhook': typeof ApiPublicYuvexpayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/final': typeof FinalRoute
  '/obrigado': typeof ObrigadoRoute
  '/obrigado2': typeof Obrigado2Route
  '/api/public/yuvexpay-webhook': typeof ApiPublicYuvexpayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/final'
    | '/obrigado'
    | '/obrigado2'
    | '/api/public/yuvexpay-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/final'
    | '/obrigado'
    | '/obrigado2'
    | '/api/public/yuvexpay-webhook'
  id:
    | '__root__'
    | '/'
    | '/final'
    | '/obrigado'
    | '/obrigado2'
    | '/api/public/yuvexpay-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FinalRoute: typeof FinalRoute
  ObrigadoRoute: typeof ObrigadoRoute
  Obrigado2Route: typeof Obrigado2Route
  ApiPublicYuvexpayWebhookRoute: typeof ApiPublicYuvexpayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/obrigado2': {
      id: '/obrigado2'
      path: '/obrigado2'
      fullPath: '/obrigado2'
      preLoaderRoute: typeof Obrigado2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/final': {
      id: '/final'
      path: '/final'
      fullPath: '/final'
      preLoaderRoute: typeof FinalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/yuvexpay-webhook': {
      id: '/api/public/yuvexpay-webhook'
      path: '/api/public/yuvexpay-webhook'
      fullPath: '/api/public/yuvexpay-webhook'
      preLoaderRoute: typeof ApiPublicYuvexpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FinalRoute: FinalRoute,
  ObrigadoRoute: ObrigadoRoute,
  Obrigado2Route: Obrigado2Route,
  ApiPublicYuvexpayWebhookRoute: ApiPublicYuvexpayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
